name: breaking_news
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  intl: ^0.18.1
  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  dio: ^5.2.1+1
  shared_preferences: ^2.0.15
  webview_flutter: ^4.2.2
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.7
  wakelock: ^0.6.2
  flutter_screenutil: ^5.8.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true